### ISSUE TITLE
Bug: branch component is broken

### ISSUE THREAD

**Issue by Shatur** [shadmansaleh/lualine.nvim#2]
### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### Actual behaviour

On Windows after e7b8b42089d662236d02fd34da7b86aa814e016e branch name updated every second and it hangs the editor.

### Aditional information

The branch name appears. Occurs in every git repo.

**Comment by shadmansaleh** [comment]
> does the branch apear on statusline ? Looking at you dotfiles I think the example you used is a submodule . Does this occur at normal repos too ?

**Comment by Shatur** [comment]
> Does the branch apear on statusline ? Looking at you dotfiles I think the example you used is a submodule . Does this occur at normal repos too ?

Yes and yes. I specified it in **Aditional information**.

**Comment by shadmansaleh** [comment]
> I specified it in Aditional information

I missed that . What's weird is that the loop I added in that commit doesn't cause a inf loop . From your output It looks like the file watch from loop is getting constantly triggered . In that case it should occur previously too as those codes are unchanged . Is it possible before that commit it still looped but you got a bit more breathing room . Maybe we should make a similar test like [this](https://github.com/hoob3rt/lualine.nvim/pull/311#issuecomment-893527581) before the offending commit.

For that you'll have to checkout to ac9a9e0a8bdac44d21ab427587f72009b9a9bc63 and put this line after [this](https://github.com/shadmansaleh/lualine.nvim/blob/ac9a9e0a8bdac44d21ab427587f72009b9a9bc63/lua/lualine/components/branch.lua#L48)

```lua
print(git_dir)
```

Also anyone else reading this if you have a windows machine let me know if you can reproduce it . Reproducing in more then one machine will confirm the bug.

**Comment by Shatur** [comment]
> For that you'll have to checkout to ac9a9e0 and put this line after this

It prints twice only when I switch between files from different repos:

```
|| .git
|| .git
|| .git
|| .git
```

**Comment by shadmansaleh** [comment]
So `finddir` is returning relative path on windows . And we are now returning absolute path . though unlikely I wonder if file watch with full path is causing an issue . We could try converting the absolute path to relative path .

You can try applying thus patch to lualine and see if the bug still happens
```diff
diff --git a/lua/lualine/components/branch.lua b/lua/lualine/components/branch.lua
index 0773334..f4053f9 100644
--- a/lua/lualine/components/branch.lua
+++ b/lua/lualine/components/branch.lua
@@ -1,6 +1,7 @@
 -- Copyright (c) 2020-2021 shadmansaleh
 -- MIT license, see LICENSE for more details.
 local Branch = require('lualine.component'):new()
+local utils = require'lualine.utils.utils'
 
 -- vars
 Branch.git_branch = ''
@@ -55,6 +56,7 @@ function Branch.find_git_dir()
       git_dir = git_file:match('(.*).git') .. git_dir
     end
   end
+  if git_dir then git_dir = utils.abs2rel_path(git_dir) end
   return git_dir
 end
 
diff --git a/lua/lualine/utils/utils.lua b/lua/lualine/utils/utils.lua
index 59da208..74a1d6e 100644
--- a/lua/lualine/utils/utils.lua
+++ b/lua/lualine/utils/utils.lua
@@ -66,4 +66,27 @@ function M.lualine_eval(id, ...)
   end
 end
 
+-- Converts a absolute path to relative path
+-- adapted from penlight
+function M.abs2rel_path(path, start)
+  local sep = package.config:sub(1,1)
+  local split, min, append = vim.split, math.min, table.insert
+  start = start or vim.fn.getcwd()
+  local startl, pathl = split(start, sep), split(path, sep)
+  local n = min(#startl, #pathl)
+  local k = n+1 -- default value if this loop doesn't bail out!
+  for i = 1, n do
+    if startl[i] ~= pathl[i] then
+      k = i
+      break
+    end
+  end
+  local rell = {}
+  for i = 1, #startl-k+1 do rell[i] = '..' end
+  if k <= #pathl then
+    for i = k,#pathl do append(rell,pathl[i]) end
+  end
+  return table.concat(rell,sep)
+end
+
 return M
```

**Comment by Shatur** [comment]
No, the issue still exists.

**Comment by shadmansaleh** [comment]
Maybe our fs checks are triggering file watch .

Let's try caching git_dirs and only look for them on BufEnter

Try this patch
```diff
diff --git a/lua/lualine/components/branch.lua b/lua/lualine/components/branch.lua
index 0773334..0cb3216 100644
--- a/lua/lualine/components/branch.lua
+++ b/lua/lualine/components/branch.lua
@@ -4,6 +4,7 @@ local Branch = require('lualine.component'):new()
 
 -- vars
 Branch.git_branch = ''
+Branch.git_dir = ''
 -- os specific path separator
 Branch.sep = package.config:sub(1, 1)
 -- event watcher to watch head file
@@ -16,22 +17,28 @@ Branch.new = function(self, options, child)
     new_branch.options.icon = '' -- e0a0
   end
   -- run watch head on load so branch is present when component is loaded
-  Branch.update_branch()
+  Branch.find_git_dir()
   -- update branch state of BufEnter as different Buffer may be on different repos
-  vim.cmd [[autocmd lualine BufEnter * lua require'lualine.components.branch'.update_branch()]]
+  vim.cmd [[autocmd lualine BufEnter * lua require'lualine.components.branch'.find_git_dir()]]
   return new_branch
 end
 
 Branch.update_status = function() return Branch.git_branch end
 
+local git_dir_cache = {}
 -- returns full path to git directory for current directory
 function Branch.find_git_dir()
   -- get file dir so we can search from that dir
   local file_dir = vim.fn.expand('%:p:h')
+  local root_dir = file_dir
   local git_file, git_dir
   -- Search upward for .git file or folder
-  while (file_dir) do
-    local git_path = file_dir..Branch.sep..'.git'
+  while (root_dir) do
+    if git_dir_cache[root_dir] then
+      git_dir = git_dir_cache[root_dir]
+      break
+    end
+    local git_path = root_dir..Branch.sep..'.git'
     local git_file_stat = vim.loop.fs_stat(git_path)
     if (git_file_stat) then
       if git_file_stat.type == 'directory' then
@@ -41,7 +48,7 @@ function Branch.find_git_dir()
       end
       break
     end
-    file_dir = file_dir:match('(.*)'..Branch.sep..'.-')
+    root_dir = root_dir:match('(.*)'..Branch.sep..'.-')
   end
 
   if git_file then
@@ -55,6 +62,11 @@ function Branch.find_git_dir()
       git_dir = git_file:match('(.*).git') .. git_dir
     end
   end
+  git_dir_cache[file_dir] = git_dir
+  if Branch.git_dir ~= git_dir then
+    Branch.git_dir = git_dir
+    Branch.update_branch()
+  end
   return git_dir
 end
 
@@ -77,7 +89,7 @@ end
 -- Update branch
 function Branch.update_branch()
   Branch.file_changed:stop()
-  local git_dir = Branch.find_git_dir()
+  local git_dir = Branch.git_dir
   if git_dir and #git_dir > 0 then
     local head_file = git_dir .. Branch.sep .. 'HEAD'
     Branch.get_git_head(head_file)
```

**Comment by Shatur** [comment]
After this patch Neovim stop hanging! But after switching folder `:Neogit` stops working that indicates that still something wrong. The fix is also unrelated to e7b8b42, so I don't think this is the correct fix...
It works just fine on the commit before or if I revert the commit. So weird... Maybe try to print everything in the branch component?

**Comment by shadmansaleh** [comment]
Check how often [this](https://github.com/shadmansaleh/lualine.nvim/blob/66b0736fd4f20c04e48dd6fc61566f696c567443/lua/lualine/components/branch.lua#L78) function is called . If this function is constently being executed or not with and without the last patch.

**Comment by Shatur** [comment]
With the patch function called the same number of times as before on every buffer change (it's called several times, but this is a separate issue).
But the editor freezes completely after changing current working directory.

I dug deeper and found differences in the return value before e7b8b42089d662236d02fd34da7b86aa814e016e and after.
Before it returns a relative path, e.g. `.git`. But after the change I get `C:\Users\Shatur\AppData\Local\nvim\pack\plugins\opt\lualine.nvim\../../../../.git/modules/pack/plugins/opt/lualine.nvim`. All this values I get by printing `git_dir` before this line:

https://github.com/shadmansaleh/lualine.nvim/blob/66b0736fd4f20c04e48dd6fc61566f696c567443/lua/lualine/components/branch.lua#L58

**Comment by shadmansaleh** [comment]
> With the patch function called the same number of times as before on every buffer change 

So that function is called for  buffer change only both with and without patch ?

We tried reletive earlier https://github.com/shadmansaleh/lualine.nvim/issues/2#issuecomment-894130530

**Comment by Shatur** [comment]
> So that function is called for buffer change only both with and without patch ?

To be more clear: the function is called to times before breaking commit and on the latest master with the patch. So, the patch fixes the problem somehow, but the editor can hang anyway after changing current directory. Looks like a lot of events triggered after the directory change.

> We tried reletive earlier #2 (comment)

Hm... Yes. let me double check the return value with the patch №1.

> return vim.fn.simplify(git_dir)

Will try too.

**Comment by shadmansaleh** [comment]
> but the editor can hang anyway after changing current directory. Looks like a lot of events triggered after the directory change.

Did you find which function it was hanging . Or at what portion of branch component it's looping ?

**Comment by Shatur** [comment]
> Hm... Yes. let me double check the return value with the patch №1.

It returns `../../../../.git/modules/pack/plugins/opt/lualine.nvim` for me while it should return just `git`.

> return vim.fn.simplify(git_dir)

Didn't work.

> Did you find which function it was hanging . Or at what portion of branch component it's looping ?

Currently not.

**Comment by shadmansaleh** [comment]
> ../../../../.git/modules/pack/plugins/opt/lualine.nvim

You're inside a submodule right ? It's suppose to return like that for submodules . Did you get `.git` returned for the submodule in original ? That should not work . 

If you're inside a submodule . There you should have a .git file that contains actual location to actual .git folder . Is it different on windows? Can you check what the contents of `.git` is in the folder you were looking at .

**Comment by Shatur** [comment]
> You're inside a submodule right ? It's suppose to return like that for submodules . Did you get .git returned for the submodule in original ? That should not work .

Oh, right, of course, `.git` folder for submodules located in the main repo. Double checked, before and after the breaking change the resulting `git_dir` is the same. So the issue is not in the path, the patch №1 is unnecessary.
I'm so sorry for confusion :)

The patch №2 fixes the problem partially. So you are right, the issue with events that called more often. Also we 100% know that the issue is caused by the changes in e7b8b42089d662236d02fd34da7b86aa814e016e.
The only thing that looks suspicious is the call `vim.loop.fs_stat(git_path)`. Can we try to replace it with vim functions, like `vim.fn.isdirectory` and `vim.fn.filereadable`? I know it's more costly, but just for check.

**Comment by shadmansaleh** [comment]
> The only thing that looks suspicious is the call vim.loop.fs_stat(git_path). Can we try to replace it with vim functions, like vim.fn.isdirectory and vim.fn.filereadable? I know it's more costly, but just for check

You can try . But will be really strange if that was the issue . After the patch with caching it shouldn't get to that point more then once . Also on that patch fs_stat can't get triggered by the event . It should have stopped it from looping if that was the issue.

**Comment by Shatur** [comment]
I edited the loop:

```lua
  while (file_dir) do
    local git_path = file_dir..Branch.sep..'.git'
    if vim.fn.isdirectory(git_path) == 1 then
      git_dir = git_path
    elseif vim.fn.filereadable(git_path) == 1
      git_file = git_path
    else
      break
    end
    file_dir = file_dir:match('(.*)'..Branch.sep..'.-')
  end
```

But after that, the branch not displayed. Could you check what is wrong with the logic?

**Comment by shadmansaleh** [comment]
```lua
if vim.fn.isdirectory(git_path) == 1 then
      git_dir = git_path
    elseif vim.fn.filereadable(git_path) == 1 then
      git_file = git_path
```
You need to break out when either of these are true . Not when both are false

**Comment by Shatur** [comment]
> You need to break out when either of these are true . Not when both are false

Oh, of course, thanks, misunderstood the original logic.
Fixed it, it works, but the issue still exists... Need to think more about it.

**Comment by Shatur** [comment]
I dug even deeper and it's crazy. It turns out that the call call `vim.fn.finddir('.git')` that was prior to e7b8b42 avoid a lot of events. I do not know why, but with this call (even if it does nothing!!!) I have the normal behavior. Check out this patch:

```diff
diff --git a/lua/lualine/components/branch.lua b/lua/lualine/components/branch.lua
index 0773334..0f1287a 100644
--- a/lua/lualine/components/branch.lua
+++ b/lua/lualine/components/branch.lua
@@ -24,7 +24,6 @@ end
 
 Branch.update_status = function() return Branch.git_branch end
 
--- returns full path to git directory for current directory
 function Branch.find_git_dir()
   -- get file dir so we can search from that dir
   local file_dir = vim.fn.expand('%:p:h')
@@ -77,6 +76,7 @@ end
 -- Update branch
 function Branch.update_branch()
   Branch.file_changed:stop()
+  vim.fn.finddir('.git') -- WTF???
   local git_dir = Branch.find_git_dir()
   if git_dir and #git_dir > 0 then
     local head_file = git_dir .. Branch.sep .. 'HEAD'
```

It fixes the issue If I apply it to the latest master. But the call `vim.fn.finddir('.git')` should be useless here!

**Comment by shadmansaleh** [comment]
> It fixes the issue If I apply it to the latest master. But the call vim.fn.finddir('.git') should be useless here!

Well it's windows . Shouldn't be too surprised :P 

I'm not sure if I can accept it as a valid fix though . Maybe it's fine if it's only ran on windows.

Try wraping that line with 
```lua
if Branch.sep == '\\' then
  -- call find dir
end
```
And see if it's still working

A nonsensical fix for a nonsensical bug 😂.

**Comment by Shatur** [comment]
No, no, it's definitely a hack 🤣 
But maybe we could use this function to find the directory somehow to make it less hacky?...
I do not understand how it related to the event that triggers this function. Gitsigns works fine for me.

**Comment by shadmansaleh** [comment]
> But maybe we could use this function to find the directory somehow to make it less hacky

I don't want to go back to finddir and findfile . There are too many downsides
1. finddir/file doesn't allow to specify start dir . Instead always uses cwd of nvim
2. Requires 2 calls (for dir & file) of which atlest one will fail or will be false positive
3. Searches both up and down the directory tree when we just care about up.
4. gets effected by 'path' option
5. Reintroduceing them will reintroduce the [bug](https://github.com/hoob3rt/lualine.nvim/issues/303) too

It's just not flexible and inefficient for what we are trying to do here .

**Comment by Shatur** [comment]
> finddir/file doesn't allow to specify start dir . Instead always uses cwd of nvim
> Requires 2 calls (for dir & file) of which atlest one will fail or will be false positive

No, `isdirectory` and `filereadable` that I used before doesn't work and unrelated. Only `finddir` somehow "hacks" it.
But something wrong with the implementation. It also called twice. Probably the best solution it to try the implementation similar to gitsigns.

**Comment by Shatur** [comment]
I think the `finddir` call that "fixes" the issue can just work as a "delay" (sleep) here. Probably we could try to suppress multiply calls.

**Comment by shadmansaleh** [comment]
> No, isdirectory and filereadable that I used before doesn't work and unrelated. Only finddir somehow "hacks" it.

I wasn't talking about them . I was talking about findfile and finddir that were used before https://github.com/shadmansaleh/lualine.nvim/commit/e7b8b42089d662236d02fd34da7b86aa814e016e

> Probably the best solution it to try the implementation similar to gitsigns.

I don't really know what gitsigns does for branch . But probably a lot more then lualine. As it keeps track of branch for all buffers while lualine only keeps trsck of current buffer . Do you know what it does ?

> I think the finddir call that "fixes" the issue can just work as a "delay" (sleep) here

You can probably test that with `uv.sleep()` .

**Comment by Shatur** [comment]
> I was talking about findfile and finddir that were used before e7b8b42

Oh, got it, thanks.

> Do you know what it does ?

Unfortunately, not.

> You can probably test that with uv.sleep() .

`vim.loop.sleep(300)` didn't help. Weird.

**Comment by shadmansaleh** [comment]
Try current master . Also the try applying the patch on top of master where you got double calls . I think I've found why it was being called twice.

**Comment by Shatur** [comment]
Tried. Still called twice.
It works ok after startup, but after changing the buffer I have 200+ calls :(

**Comment by shadmansaleh** [comment]
I'm out of idea for this one 😞

**Comment by Shatur** [comment]
Me to... Will use gitsigns for branch component. It will also allow to avoid parsing branch twice for each plugin. Maybe someone will come up with solution.

**Comment by shadmansaleh** [comment]
Try this patch. I've dropped file watch for windows . If this still loops . I don't what won't :D .

```diff
diff --git a/lua/lualine/components/branch.lua b/lua/lualine/components/branch.lua
index b7e8af2..4a2d00a 100644
--- a/lua/lualine/components/branch.lua
+++ b/lua/lualine/components/branch.lua
@@ -4,10 +4,13 @@ local utils = require('lualine.utils.utils')
 local Branch = require('lualine.component'):new()
 -- vars
 Branch.git_branch = ''
+Branch.git_dir = ''
 -- os specific path separator
 Branch.sep = package.config:sub(1, 1)
 -- event watcher to watch head file
-Branch.file_changed = vim.loop.new_fs_event()
+-- Use file wstch for non windows and poll for windows.
+-- windows doesn't like file watch for some reason.
+Branch.file_changed = Branch.sep ~= "\\" and vim.loop.new_fs_event() or vim.loop.new_fs_poll()
 Branch.active_bufnr = '0'
 local branch_cache = {} -- stores last known branch for a buffer
 -- Initilizer
@@ -17,9 +20,9 @@ Branch.new = function(self, options, child)
     new_branch.options.icon = '' -- e0a0
   end
   -- run watch head on load so branch is present when component is loaded
-  Branch.update_branch()
+  Branch.find_git_dir()
   -- update branch state of BufEnter as different Buffer may be on different repos
-  utils.define_autocmd('BufEnter', "lua require'lualine.components.branch'.update_branch()")
+  utils.define_autocmd('BufEnter', "lua require'lualine.components.branch'.find_git_dir()")
   return new_branch
 end
 
@@ -34,14 +37,20 @@ Branch.update_status = function(_, is_focused)
   return Branch.git_branch
 end
 
+local git_dir_cache = {} -- Stores git paths that we already know of
 -- returns full path to git directory for current directory
 function Branch.find_git_dir()
   -- get file dir so we can search from that dir
   local file_dir = vim.fn.expand('%:p:h')
+  local root_dir = file_dir
   local git_file, git_dir
   -- Search upward for .git file or folder
-  while (file_dir) do
-    local git_path = file_dir..Branch.sep..'.git'
+  while (root_dir) do
+    if git_dir_cache[root_dir] then
+      git_dir = git_dir_cache[root_dir]
+      break
+    end
+    local git_path = root_dir..Branch.sep..'.git'
     local git_file_stat = vim.loop.fs_stat(git_path)
     if (git_file_stat) then
       if git_file_stat.type == 'directory' then
@@ -51,7 +60,7 @@ function Branch.find_git_dir()
       end
       break
     end
-    file_dir = file_dir:match('(.*)'..Branch.sep..'.-')
+    root_dir = root_dir:match('(.*)'..Branch.sep..'.-')
   end
 
   if git_file then
@@ -65,6 +74,11 @@ function Branch.find_git_dir()
       git_dir = git_file:match('(.*).git') .. git_dir
     end
   end
+  git_dir_cache[file_dir] = git_dir
+  if Branch.git_dir ~= git_dir then
+    Branch.git_dir = git_dir
+    Branch.update_branch()
+  end
   return git_dir
 end
 
@@ -88,15 +102,21 @@ end
 function Branch.update_branch()
   Branch.active_bufnr = tostring(vim.fn.bufnr())
   Branch.file_changed:stop()
-  local git_dir = Branch.find_git_dir()
+  local git_dir = Branch.git_dir
   if git_dir and #git_dir > 0 then
     local head_file = git_dir .. Branch.sep .. 'HEAD'
     Branch.get_git_head(head_file)
-    Branch.file_changed:start(head_file, {}, vim.schedule_wrap(
-                                  function()
-          -- reset file-watch
-          Branch.update_branch()
-        end))
+    if Branch.sep ~= "\\" then
+      Branch.file_changed:start(head_file, {}, vim.schedule_wrap( function()
+        -- reset file-watch
+        Branch.update_branch()
+      end))
+    else
+      Branch.file_changed:start(head_file, 1000, vim.schedule_wrap( function()
+        -- reset file-watch
+        Branch.update_branch()
+      end))
+    end
   else
     -- set to '' when git dir was not found
     Branch.git_branch = ''
```

**Comment by Shatur** [comment]
> Try this patch. I've dropped event watch for windows instead using polls. If event watch on windows is buggy this patch should fix this issue.

Now works as expected!

**Comment by shadmansaleh** [comment]
Great now I can merge it .

**Comment by shadmansaleh** [comment]
Can you hide these two comments ?
 - https://github.com/hoob3rt/lualine.nvim/pull/311#issuecomment-893567224
 - https://github.com/hoob3rt/lualine.nvim/pull/311#issuecomment-893364853

**Comment by Shatur** [comment]
Thanks! Sure.

**Comment by shadmansaleh** [comment]
Welcome . Also one more tips since you've liked using `gitsigns` for `branch`. You can use gitsigns (actually anything that keeps track of diffs) as source for `diff` component. I had added `source` option to `diff` few days ago. I'm currently using `gitsigns` for `diff` with something like this.

```lua
local function diff_source()
  local gitsigns = vim.b.gitsigns_status_dict
  if gitsigns then
    return {
      added = gitsigns.added,
      modified = gitsigns.changed,
      removed = gitsigns.removed
    }
  end
end
require'lualine'.setup {
  sections = {
    lualine_b = { {'diff', source = diff_source}, },
  }
}
```

**Comment by Shatur** [comment]
Wow, did not know, thank you. Can we have a predefined function for it? I bet that gitsigns is wide used :)

**Comment by shadmansaleh** [comment]
> Can we have a predefined function for it? 

I don't want to put specific plugin support . Instead I want provide interfaces so they can be reused for things that I didn't even think of while writting the interfaces.

Currently gitsigns is popular it might not be tomorrow . There are several other plugins that provide diffs that are popular too . If I add one then others will demand support for other plugins too . Then when those plugins go out of cycle the specific integrations becomes rarely used code that need to be maintained. I don't want lualine to become airline . Hopefully you can understand :)

**Comment by Shatur** [comment]
Fair point, thanks!
