### ISSUE TITLE
Coloring Lualine with highlight groups

### ISSUE THREAD

**Issue by cpkio** [shadmansaleh/lualine.nvim#29]
Could you please explain, if its possible to bind Lualine colors to highlight groups? This `Instead of defining colors as table containing values you can define it as a string. This string is considered a highlight group name and lualines highlight is linked to that group.` needs some example code to understand.

**Comment by shadmansaleh** [comment]
like theme defined by clason [here](https://gist.github.com/clason/5a8f57d81525d015ef1abfb276a78974#file-lualine-lua-L4-L8)

**Comment by cpkio** [comment]
Section separators seem to dissappear if colors are defined via highlight groups.

```
require('lualine').setup({
  sections = {
    lualine_a = { {'mode', lower = false } },
    lualine_b = { 'branch'},
    lualine_c = { { 'getcwd' }, {'filename', color = "PmenuSelBold" }, { '%B', color = "SpecialKey" } },
    lualine_x = { 'encoding', 'fileformat', 'filetype' },
    lualine_y = { 'progress' },
    lualine_z = { 'location' }
  },
  options = {
    theme = {
      normal = { a = 'statusOuter', b = 'statusMiddle', c = 'statusInner' },
      insert = { a = 'statusInsert' },
      visual = { a = 'statusVisual' },
      replace = { a = 'statusReplace' },
      command = { a = 'statusCommand' },
      inactive = { a = 'statusInactive', b = 'statusInactive', c = 'statusInactive' },
    },
    section_separators = { '+', '+' },
    component_separators = { '-', '-' },
  }
})
```
The status line is ` NORMAL  C:\Users\user  [No Name]  0` … `utf-8 -   All    0:0`

No section or component separators in left part, and no section separators on the right.

**Comment by cpkio** [comment]
Oh, I see. If no bg is provided in highlight, this fails. And separator colors are calculated, not taken from highlight groups. The first is OK.

**Comment by shadmansaleh** [comment]
> Can something be done with transitionals, so they would take hl group?

Nope. You need to have proper bg in hl that you want to transition from and to .

**Comment by shadmansaleh** [comment]
Not taking separator color from users is a design decision . I've explained the reasoning [here](https://github.com/hoob3rt/lualine.nvim/issues/324#issuecomment-907806262) . If you think Taking colors from users is better , you can reopen the issue and expkain why .
