### ISSUE TITLE
Bug: lualine won't show branch component when open a file for the first time.

### ISSUE THREAD

**Issue by AnthonyK213** [shadmansaleh/lualine.nvim#38]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Open a file in a git directory using `:e xxx/file/path` with cwd outside the git root.

### Expected behaviour
The branch component should show immediately after opening the file.

### Actual behaviour
The branch component does not show for the first time, I need to open another file to get it work.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
I can reproduce this . branch shows up as soon as the buffer inside a git repo is loaded.

What do you exactly mean by this ? 
> Open a file in a git directory using :e xxx/file/path with cwd outside the git root.

Did you manage to reproduce it in a clean environment ?
Did you try the script on issue template ?
Did you try in a completely new git repo ?
You'll have to provide a better way to reproduce this cause this is not the behavior that I'm seeing.

**Comment by AnthonyK213** [comment]
Sorry for my poor explanation... I mean, start neovim with the cwd not inside any git repository, and then use `:edit file/path` to open a file which is inside a git repository, in my case, even though I tried to use a minimized configuration, the branch component did not work at the first time. (Tested on fedora, windows and termux)

**Comment by shadmansaleh** [comment]
I can reproduce it now I'll take a look why it's happing.

**Comment by shadmansaleh** [comment]
Can you confirm it's been fixed ?

**Comment by AnthonyK213** [comment]
Fixed, thanks!
