### ISSUE TITLE
Feat: Show diagnostic "idle" status when no messages

### ISSUE THREAD

**Issue by roginfarrer** [shadmansaleh/lualine.nvim#43]
### Requested feature

One thing I'd love is the option to have an "idle" state for the diagnostics component when there are no errors, hints, warnings etc to show. Right now if there are no messages, nothing is presented. 

### Motivation

One way to know if your LSP is connected and working properly is if there are errors/warnings in the file. But if everything in your file is passing the diagnostics, there's not a good way of knowing that your LSPs are connected and working. I think the statusline is the appropriate place to communicate that the LSPs are connected and listening for diagnostic issues.

**Comment by shadmansaleh** [comment]
diagnostics component can use multiple sources at the same time what happens when some source is working and some isn't ? Also what should the indicator be shoeing 0,0,0,0 ?

What lsp are you using? If you're using native lsp you can try the [lsp server component](https://github.com/shadmansaleh/lualine.nvim/blob/1f4df948c4a95e5ed276a29f6916e46735ff411a/examples/evil_lualine.lua#L156-L172 from evilline.

**Comment by roginfarrer** [comment]
Thanks for that snippet, that was useful. It was pretty similar to what I had put together:

```lua
local function lsp_client_names()
	local msg = 'no active lsp'

	if #vim.lsp.buf_get_clients() then
		local clients = {}
		for _, client in pairs(vim.lsp.get_active_clients()) do
			table.insert(clients, client.name)
		end

		if next(clients) == nil then
			return msg
		end

		local bufnr = vim.api.nvim_get_current_buf()
		local count = vim.lsp.diagnostic.get_count(bufnr, 'Error')
		count = count + vim.lsp.diagnostic.get_count(bufnr, 'Warning')
		count = count + vim.lsp.diagnostic.get_count(bufnr, 'Info')
		count = count + vim.lsp.diagnostic.get_count(bufnr, 'Hint')

		if count == 0 then
			return ' LSP: ' .. table.concat(clients, ',')
		else
			return ''
		end
	end

	return msg
end
```

**Comment by roginfarrer** [comment]
Thanks for that snippet, it's pretty similar to what I had put together:

```lua
local function lsp_client_names()
	local msg = 'no active lsp'

	if #vim.lsp.buf_get_clients() then
		local clients = {}
		for _, client in pairs(vim.lsp.get_active_clients()) do
			table.insert(clients, client.name)
		end

		if next(clients) == nil then
			return msg
		end

		local bufnr = vim.api.nvim_get_current_buf()
		local count = vim.lsp.diagnostic.get_count(bufnr, 'Error')
		count = count + vim.lsp.diagnostic.get_count(bufnr, 'Warning')
		count = count + vim.lsp.diagnostic.get_count(bufnr, 'Info')
		count = count + vim.lsp.diagnostic.get_count(bufnr, 'Hint')

		if count == 0 then
			return ' LSP: ' .. table.concat(clients, ',')
		else
			return ''
		end
	end

	return msg
end
```

I think the idea would be to have something show when there's no diagnostics present. Maybe by default it's just a checkmark, or something like: "LSP: ✅"? (Using a nerdfont instead of emoji). Then that fallback icon/content could be configured with the `sections` and `symbols` option.

Though I understand it might be hard to make a solution that makes sense for everyone, and perhaps it's better to have to customize it yourself, like I'm doing.

**Comment by shadmansaleh** [comment]
The thing is diagnostics component supports various types of sources and not everything is LSP .

Also with sources option users can integrate anything by bridging with a function . Now I really don't know how this can work for all those . native-lsp provides a nice api to access all those info but I don't know if it's possible for coc/ale/others. it's probably impossible for function sources .

For this to be added this will have to be implemented for all kinds of sources diagnostics supports that's what makes it hard.

Also what would happen if you've configured diagnostics to use nvim-lsp & ALE as source and say nvim-lsp fails but ale is working what would it show then ?

**Comment by roginfarrer** [comment]
Gotcha, I understand the complexity now. I'll close this issue out, maybe someone else will find the snippets valuable if they want to create something similar!
