### ISSUE TITLE
Bug: evil_lualine branch does not display properly

### ISSUE THREAD

**Issue by DemoorBug** [shadmansaleh/lualine.nvim#54]
Already switched to [examples/evil_lualine.lua](https://github.com/shadmansaleh/lualine.nvim/blob/master/examples/evil_lualine.lua)
[Same question](https://gist.github.com/hoob3rt/b200435a765ca18f09f83580a606b878#gistcomment-3895107)
Still not displaying branch properly, and a new error has appeared:

![Snipaste_2021-09-16_20-47-35](https://user-images.githubusercontent.com/18387615/133616457-b86f1abf-ca2c-4cc6-925a-9e105f72abe1.png)

**Comment by shadmansaleh** [comment]
You still haven't answered my original questions.

Are you using the evilline from this repo ?

Also is it something only happens on that specific repo?

**Comment by DemoorBug** [comment]
Yes, I am using evilline from this repo.
Every repo has this problem.

**Comment by shadmansaleh** [comment]
Can you remove the `cond` line [here](https://github.com/shadmansaleh/lualine.nvim/blob/2f801ed6221abfb00f74e34c35ccd4d1153c2b07/examples/evil_lualine.lua#L196) and see if it still occures?

**Comment by DemoorBug** [comment]
> Can you remove the `cond` line [here](https://github.com/shadmansaleh/lualine.nvim/blob/2f801ed6221abfb00f74e34c35ccd4d1153c2b07/examples/evil_lualine.lua#L196) and see if it still occurs?

Delete this and it will be displayed normally, thanks, close this
