### ISSUE TITLE
Feat: support new diagnostic highlights

### ISSUE THREAD

**Issue by clason** [shadmansaleh/lualine.nvim#56]
In https://github.com/neovim/neovim/pull/15585, the name of the diagnostic highlight groups was renamed:
* `LspDiagnosticsDefaultError` -> `DiagnosticError`
* `LspDiagnosticsDefaultWarning` -> `DiagnosticWarn`
* `LspDiagnosticsDefaultInformation` -> `DiagnosticInfo`
* `LspDiagnosticsDefaultHint` -> `DiagnosticHint`

It would be good to preferentially use these in the diagnostic component if they are defined.

**Comment by shadmansaleh** [comment]
> DiagnosticErrorWarn

That feels strange . Why isn't it just DiagnosticWarn ??

**Comment by clason** [comment]
Copy-pasta 🤦🏻 

Fixed!

**Comment by shadmansaleh** [comment]
Might interest you https://github.com/shadmansaleh/lualine.nvim/commit/c5cb601a6ac3390c9e872c19a54f7371aa61f542

I'm not sure what happens to `nvim_lsp` diagnostics source . It'll show only diagnostics from lsp but with deprecated method. Maybe I'll deprecate/remove it once `vim.diagnostics` is released .

**Comment by clason** [comment]
Not sure whether it'll be backported to 0.5.x; but I assume as soon as `null-ls` and friends switch over, there will be demand (probably for more configurability like per-namespace components).

**Comment by clason** [comment]
Also related: https://github.com/neovim/neovim/pull/15585#issuecomment-921915592

**Comment by shadmansaleh** [comment]
Didn't know about `DiagnosticsChanged` event was that added in that pr ? Sounds great, I'll put that in my list of things to checkout . Thanks

**Comment by clason** [comment]
Yep, that's a new event.
