### ISSUE TITLE
Bug: selecting a theme is broken by latest neovim

### ISSUE THREAD

**Issue by dimbleby** [shadmansaleh/lualine.nvim#57]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

```
require('lualine').setup {
  options = {
    icons_enabled = false,
    theme = 'gruvbox'
  }
}
```

### Expected behaviour

No errors, use gruvbox theme

### Actual behaviour

```
E5108: Error executing lua ...k/packer/start/lualine.nvim/lua/lualine/utils/loader.lua:232: lua/lualine/themes/gruvbox.lua Not found
```

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

### Aditional information

https://github.com/neovim/neovim/issues/15714

It's currently not clear to me whether neovim broke this deliberately or accidentally, will close this issue in the event that it was accidental and is reverted.

**Comment by dimbleby** [comment]
https://github.com/neovim/neovim/issues/15714

It's currently not clear to me whether neovim broke this deliberately or accidentally, will close this issue in the event that it was accidental and is reverted.

**Comment by dimbleby** [comment]
perhaps one is supposed to use `nvim_get_runtime_file()` now, making `rtp_searcher` redundant?

**Comment by goolord** [comment]
i opened a pr with a patch that fixes this for `HEAD` neovim, not sure if it's ok to break lualine for older nvim but at the very least anyone who wants the patch can use it in the meantime
