### ISSUE TITLE
Bug: My Quickfix extension doesn't work

### ISSUE THREAD

**Issue by rafi** [shadmansaleh/lualine.nvim#6]
After switching to this fork, my custom Quickfix extension stopped working, and I see the default quickfix statusline instead.

```lua
-- Detect quickfix vs. location list
local function is_loclist()
	return vim.fn.getloclist(0, {filewinid = 1}).filewinid ~= 0
end

-- Extension: Quickfix
local extension_quickfix = {
	sections = {
		lualine_a = {
			{
				function()
					local q = '  '
					local l = '  '
					return is_loclist() and l..'Location List' or q..'Quickfix List'
				end,
				right_padding = 0,
			},
			{
				function()
					if is_loclist() then
						return vim.fn.getloclist(0, {title = 0}).title
					end
					return vim.fn.getqflist({title = 0}).title
				end
			},
		},
		lualine_z = { function() return '%l/%L' end },
	},
	filetypes = {'qf'},
}
```

**Comment by shadmansaleh** [comment]
After https://github.com/shadmansaleh/lualine.nvim/commit/fac96d71cca25b4c4fb286caee024bc1e8246a25 
You'll have to put
```lua
vim.g.qf_disable_statusline = true
```

somewhere in your config for this to work. After that commit lualine doesn't aggrasively hokd onto statusline option . This allows different statusline for different things . Here defult ft plugin for quickfix is setting the statusline option that you don't want . So you need to tell it not to do that .

**Comment by rafi** [comment]
Thanks @shadmansaleh, that works.
Where is this variable referenced? which part of the code checks it?

**Comment by shadmansaleh** [comment]
This part https://github.com/neovim/neovim/blob/6f0d4ccc43d7c8f5dd72d0d83e54e947d05117fa/runtime/ftplugin/qf.vim#L13-L18 .

It maybe mentioned some where in help docs . I got there with `:verbose setl stl`.

This issue can be closed I believe.
