### ISSUE TITLE
Bug: Lualine tab number doesn't change according to the buffers

### ISSUE THREAD

**Issue by ashincoder** [shadmansaleh/lualine.nvim#66]
![2021-09-20-194027_1366x768_scrot](https://user-images.githubusercontent.com/83629316/134017631-e42d1fb2-69fd-4ac1-9319-4d1f738a1519.png)

This is the behaviour after using tabline. The tab number doesn't change when changing the buffer.

https://user-images.githubusercontent.com/83629316/134018996-7ed64321-134d-4356-b68e-11cb28fed568.mp4

**Comment by ashincoder** [comment]
I do have the stable version of neovim 0.5 and the latest lualine commit.

**Comment by shadmansaleh** [comment]
I'm not sure what you're saying . You haven't changed tabs why would tab no change ?

I don't see a bug here . As far as I can see it's behaving as intended

I think you have confusion about concept of tabs in vim/neovims context.

In neovim/vim tabs aren't mapped to a single buffer . Instead it's a view that can be composed of multiple buffers & windows.

Checkout `:h tabpages`

**Comment by ashincoder** [comment]
@shadmansaleh clearly I have 2 tabs

**Comment by ashincoder** [comment]
Still it shows no. 1

**Comment by shadmansaleh** [comment]
You have 2 buffers and 1 tab.

**Comment by shadmansaleh** [comment]
You can create tab with `:tabnew`

**Comment by ashincoder** [comment]
so buffers and tabs are different I see. I read the docs now. (not full lul).

**Comment by ashincoder** [comment]
@shadmansaleh another issue. This is caused when in the "alpha" filetype.

**Comment by shadmansaleh** [comment]
> @shadmansaleh another issue. This is caused when in the "alpha" filetype.

fixed in cdc574c9b0c2803e3d1786f4b6f317782b12fadc
