### ISSUE TITLE
Bug: LualineNotices

### ISSUE THREAD

**Issue by CantoroMC** [shadmansaleh/lualine.nvim#68]
I've just moved to this fork of lualine, when adjusting the configuration, I 've noticed:
1. There is a spell error of the word deprecated
2. You should consider make the helper buffer ReadOnly

**Comment by shadmansaleh** [comment]
> There is a spell error of the word deprecated

Do remember which which notice it was or what the wrong spell was ?

> You should consider make the helper buffer ReadOnly

This is a good idea .

**Comment by CantoroMC** [comment]
lua/lualine/config.lua
31:33:local function check_sep_format_deprication(sep)
35:48:Using list for configuring separators has been depricated. Please configure it
49:31:      return check_sep_format_deprication(separators)
