### ISSUE TITLE
Reloading init.lua loads an unrelated theme if theme is set to "auto"

### ISSUE THREAD

**Issue by oblitum** [shadmansaleh/lualine.nvim#7]
Meaning `"auto"` won't follow colorscheme on init reload (and after `:PackerSync`, `:PackerCompile`, etc).

**Comment by shadmansaleh** [comment]
I can not reproduce this . May be it has something to do with your config . Do you set your coloscheme before your setup call to lualine ?

**Comment by oblitum** [comment]
> Do you set your coloscheme before your setup call to lualine ?

@shadmansaleh I've just put a `vim.cmd [[colorscheme rose-pine]]` right before `require('lualine').setup {`, still same issue.

**Comment by shadmansaleh** [comment]
Then you'll have to share you're config . Cause it works fine inside mine :D

**Comment by oblitum** [comment]
Okay, in trying to recreate a minimal init I found the culprit, and it's my fault (and quite obvious: have it lazy loaded only at `event = 'CursorMoved'`), so, sorry for the noise.
