### ISSUE TITLE
Feat: Add filename option to not shorten path segments

### ISSUE THREAD

**Issue by itmecho** [shadmansaleh/lualine.nvim#8]
### Requested feature
Add option to the filename component to disable path shortening

### Motivation
It would be nice to have the option to disable filename path shortening as that information is really useful, especially when I'm on a wide screen that has more than enough room.

**Example:**
![image](https://user-images.githubusercontent.com/8384983/129334752-3f86e5b7-402f-4b3a-a766-d2ac341abd8e.png)

```lua
lualine_c = {
    {"filename", path = 1}
},
```

**Comment by shadmansaleh** [comment]
I think this won't be an issue once we merge https://github.com/hoob3rt/lualine.nvim/pull/265 .

Also I want to expose `estimated_total_width_of_decorations` variable in that pr as an option (Need a good name for it though) .

**Comment by wimstefan** [comment]
What about `estimated_available_space`?

**Comment by shadmansaleh** [comment]
> What about estimated_available_space?

Is that a name suggestion ? If it is I think it's too long and doesn't exactly express what it's going to do .

**Comment by wimstefan** [comment]
> > What about estimated_available_space?
> 
> Is that a name suggestion ? If it is I think it's too long and doesn't exactly express what it's going to do .

Yes it was a suggestion indeed ;) 
Obviously a bad one since I can only guess what that variable is all about. Sorry about that.

**Comment by shadmansaleh** [comment]
Sorry I should have explained what it was :P , Basically say when you set it to 50 . Lualine will try to keep the path length below that .But it's not a hard requirement rather a soft requirement . When path gets longer then 50 it'll collapse a chunk of path to shorten it .

**Comment by shadmansaleh** [comment]
Set `shorting_target` option in filename to 0 . It'll disable path shorting .

**Comment by wimstefan** [comment]
Thanks for the explanation! 
Since you're asking even in the commit for other suggestions for the new variable I'll give it another go: `path_limits`
I hope this is more in the line of how you designed the new functionality ...

**Comment by shadmansaleh** [comment]
Actually I didn't designe it . Also I was a bit wrong how I understood it before . After reading the code what I got is it's an indicator of how much space path should leave in the window . For example you have 120 char wide window and you set the value to 50 then it'll try to leave 50 chars empty and shorten itself to fit in 70 chars . This seems a bit weird to me lol . `path_limits` was decent for what I explained earlier . But I think `path_limits1 doesn't hint what it's actual behaviour is. Thanks for trying though :)

**Comment by wimstefan** [comment]
Thanks for the details!

After having read your explanation I think `path_limits` is too complicated indeed because you have to think twice before you understand that the path length is limited negatively by the used value.

What about these suggestions?
`keep_space`
`space_available`
`white_space`

I hope it is OK for you if I keep coming up with suggestions - since I'm not a programmer that's the only way (together with reporting issues) to contribute to your fantastic work! Please say so if you want me to stop it.

**Comment by shadmansaleh** [comment]
> I hope it is OK for you if I keep coming up with suggestions - since I'm not a programmer that's the only way (together with reporting issues)

You can keep them coming . Bug Reports are really useful . It's not possible for me to find the bugs without them .

I think I'll change the mechanics a bit to make it easier to understand . Current mechanics for path shorting limit is hard to understand and explain .
